### PR TITLE
use const Function

### PR DESCRIPTION
**Pull request by aeslaughter**

### CODE REVIEW

**Comment by pou036** [comment]
Hi Andrew,
Thanks for the fix. Could you please update the test file "tests/NS/test_RedbackNS.i"  and add a missing dash in front of "ksp_atol" line 117? (You can also get rid of line 120 "line_search = cp")
Apparently PETSc no longer ignores wrong commands (which is good), so that old mistake resurfaces...
Cheers,
Thomas.

**Comment by pou036** [comment]
Hi @aeslaughter, please see comment above. Thomas.

**Comment by aeslaughter** [comment]
@pou036 Ready for you to activate

**Comment by pou036** [comment]
Thanks @aeslaughter !

**Pull request merged**
